#!/usr/bin/env python3
"""
mojibake_fix.py — heals UTF-8-as-Windows-1252 double-encoding corruption.

WHAT THIS FIXES
---------------
When UTF-8 source files are read by an editor or tool that thinks they're
Windows-1252 (cp1252) and then re-saved as UTF-8, every multi-byte character
gets shredded into a sequence of 2-3 garbled characters. Examples:

    star    becomes  three-char garble starting with a-with-circumflex
    multiplication X    becomes  similar three-char garble
    green circle emoji   becomes  four-char garble starting with eth
    em dash    becomes  three-char garble
    curly apostrophe    becomes  three-char garble

This is fully reversible: encode the corrupted text with cp1252 to recover
the original bytes, then decode those bytes as UTF-8.

USAGE
-----
    python mojibake_fix.py <repo_root>            # dry run, shows what would change
    python mojibake_fix.py <repo_root> --apply    # writes fixed files (with .bak backups)
    python mojibake_fix.py <repo_root> --apply --no-backup    # skip backups

Walks the directory, finds source files (.jsx .tsx .js .ts .css .html .md .json),
skips node_modules/.git/dist/build, attempts to heal each one, and only writes
the file if the heal actually reduces the count of mojibake markers (so it
won't ever make a clean file worse).

PROJECT NOTE
------------
Built for the CircumSurvey mono-repo consolidation cleanup, April 2026.
After running this on a repo with corruption, run `npm run build` and verify
the output bundle no longer contains mojibake before pushing.
"""

import argparse
import sys
from pathlib import Path

# Mojibake markers - finding any of these in a file means it's a candidate.
# These are the corrupted forms generated by encoding common Unicode
# characters as UTF-8 then mis-decoding the bytes as cp1252.
SENTINEL_MARKERS = [
    "\u00e2\u02dc\u2026",   # corrupted star
    "\u00e2\u0153\u2022",   # corrupted multiplication X
    "\u00e2\u0153\u017d",   # corrupted pencil
    "\u00e2\u2014\u02c6",   # corrupted diamond
    "\u00e2\u2122\u00a5",   # corrupted heart
    "\u00e2\u2013\u00be",   # corrupted down-triangle
    "\u00e2\u2021\u201d",   # corrupted left-right arrow
    "\u00e2\u20ac\u201d",   # corrupted em-dash
    "\u00e2\u20ac\u201c",   # corrupted en-dash
    "\u00e2\u20ac\u2122",   # corrupted right-single-quote
    "\u00e2\u20ac\u0153",   # corrupted left-double-quote
    "\u00e2\u20ac\u00a6",   # corrupted ellipsis
    "\u00c2\u00b7",          # corrupted middle-dot
    "\u00e2\u017e\u201d",   # corrupted right-arrow (heavy)
    "\u00e2\u2020\u2019",   # corrupted right-arrow (light)
    "\u00f0\u0178\u0178",   # corrupted emoji prefix (4-byte UTF-8 family)
    "\u00f0\u0178\u201d",   # corrupted emoji prefix variant
    "\u00e2\u0161\u00aa",   # corrupted white-circle
]

EXTENSIONS = {".jsx", ".tsx", ".js", ".ts", ".css", ".html", ".md", ".json"}
SKIP_DIRS = {"node_modules", ".git", "dist", "build", ".cache", ".next", ".turbo", ".vercel"}


def count_markers(text: str) -> int:
    return sum(text.count(m) for m in SENTINEL_MARKERS)


def heal(text: str) -> str:
    """
    Reverse UTF-8-as-cp1252 double encoding.

    Encode the codepoints back to cp1252 bytes (which is what the original
    UTF-8 bytes were), then decode those bytes as UTF-8.

    Returns the healed string only if it reduces the mojibake marker count.
    Otherwise returns the original - so we never make a file worse.
    """
    try:
        healed = text.encode("cp1252", errors="strict").decode("utf-8", errors="strict")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text  # Mixed/partial content - leave it for manual review
    if count_markers(healed) < count_markers(text):
        return healed
    return text


def main():
    parser = argparse.ArgumentParser(
        description="Heal UTF-8-as-Windows-1252 double-encoding in source files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("root", help="Repo root directory to walk")
    parser.add_argument("--apply", action="store_true",
                        help="Actually write fixes (default is dry-run)")
    parser.add_argument("--no-backup", action="store_true",
                        help="Skip writing <file>.bak")
    parser.add_argument("--ext", action="append", default=[],
                        help="Extra extensions to include, e.g. --ext .vue")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print("ERROR: {} is not a directory".format(root), file=sys.stderr)
        sys.exit(2)

    extensions = EXTENSIONS | {
        e if e.startswith(".") else "." + e for e in args.ext
    }

    affected = []
    skipped_unhealable = []

    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix.lower() not in extensions:
            continue
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            print("  ?  {} is not valid UTF-8 - skipping".format(p.relative_to(root)))
            continue

        before = count_markers(text)
        if before == 0:
            continue

        healed = heal(text)
        if healed == text:
            skipped_unhealable.append((p, before))
            continue
        after = count_markers(healed)
        affected.append((p, before, after, healed))

    if skipped_unhealable:
        print("\n{} file(s) have markers but couldn't be auto-healed:".format(len(skipped_unhealable)))
        for p, n in skipped_unhealable:
            print("  ?  {}  ({} markers)".format(p.relative_to(root), n))
        print("    These need manual inspection - they may have mixed encoding.\n")

    if not affected:
        print("No additional files need healing.")
        return

    print("\nFound {} file(s) that can be healed:\n".format(len(affected)))
    for p, before, after, _ in affected:
        rel = p.relative_to(root)
        delta = before - after
        print("  {}".format(rel))
        print("      mojibake markers: {} -> {}  (healing {})".format(before, after, delta))

    if not args.apply:
        print("\n[DRY RUN] No files written. Re-run with --apply to write changes.")
        return

    print("\nWriting {} file(s)...".format(len(affected)))
    for p, _, _, healed in affected:
        if not args.no_backup:
            backup = p.with_suffix(p.suffix + ".bak")
            if not backup.exists():
                backup.write_bytes(p.read_bytes())
        p.write_text(healed, encoding="utf-8", newline="")
        print("  OK  {}".format(p.relative_to(root)))

    if not args.no_backup:
        print("\nDone. Backups saved as <file>.bak.")
        print("After verifying the fix is correct, you can delete backups:")
        print('  PowerShell:  Get-ChildItem -Recurse -Filter *.bak | Remove-Item')
        print('  Bash:        find . -name "*.bak" -delete')
    else:
        print("\nDone. No backups created.")


if __name__ == "__main__":
    main()
