BEGIN TRANSACTION;
UPDATE entities SET role = 'Organization' WHERE id = 'entity-de9a2af3';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-f527b612';
UPDATE entities SET role = 'Advocacy Group' WHERE id = 'entity-5761b449';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-47c9a86f';
UPDATE entities SET role = 'Medical Professional' WHERE id = 'entity-f8d50671';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-79868ea4';
UPDATE entities SET role = 'Medical Professional' WHERE id = 'entity-7c3798e5';
UPDATE entities SET role = 'Medical Professional' WHERE id = 'entity-ddb9417e';
UPDATE entities SET role = 'Medical Professional' WHERE id = 'entity-07c26a90';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-e0893973';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-bd9baa19';
UPDATE entities SET role = 'Medical Professional' WHERE id = 'entity-8132c435';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-907d0e24';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-7d04c46d';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-9fd64644';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-b7e4ce31';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-c4c3df5e';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-bb816399';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-233c47f3';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-619de159';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-07413104';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-7e2d80d7';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-b892fbc8';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-a8a849f1';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-32ddf3f2';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-fef45123';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-5c9f527b';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-533370ca';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-554d9584';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-c3f36091';
UPDATE entities SET role = 'Advocacy Group' WHERE id = 'entity-c987281d';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-7b591bb3';
UPDATE entities SET role = 'Advocacy Group' WHERE id = 'entity-981216bf';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-a65645f0';
UPDATE entities SET role = 'Government / Legal Body' WHERE id = 'entity-2fd5437f';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-d604e3f2';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-64ffee09';
UPDATE entities SET role = 'Medical Organization' WHERE id = 'entity-2d44216d';
UPDATE entities SET role = 'Organization' WHERE id = 'entity-ab7f28e0';
UPDATE entities SET role = 'Research Institution' WHERE id = 'entity-5be69455';
UPDATE entities SET role = 'Research Institution' WHERE id = 'entity-fe920aa9';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-4472ef27';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-08fe2866';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-3caa8d2c';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-0d610ac0';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-911c66a6';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-e11c48d3';
UPDATE entities SET role = 'Author / Journalist' WHERE id = 'entity-81ad91e4';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-d2b584dd';
UPDATE entities SET role = 'Individual' WHERE id = 'entity-f6311a58';
COMMIT;