name = "advocacy-shell"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-20"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "ARCHIVE_BUCKET"
bucket_name = "advocacy-archive"
preview_bucket_name = "advocacy-archive-preview"


[[d1_databases]]
binding = "SURVEY_DB"
database_name = "circumsurvey"
database_id = "9018c642-05c8-4335-93cc-4282c5e7ff12"
preview_database_id = "circumsurvey"

[[vectorize]]
binding = "ARCHIVE_INDEX"
index_name = "archive-index"
