// ═══════════════════════════════════════════════════════════════
// CircumSurvey — Auto-generated aggregate data
// Generated: 2026-04-17 08:43 UTC
// DO NOT EDIT MANUALLY — regenerated by scripts/aggregate.py
// ═══════════════════════════════════════════════════════════════

const _data = {
  "meta": {
    "totalRespondents": 496,
    "phase": "Phase 1 · Preliminary Findings",
    "lastUpdated": "2026-04-17",
    "pathwayCounts": {
      "intact": 140,
      "restoring": 109,
      "circumcised": 210,
      "observer": 37
    }
  },
  "pathway": {
    "intact": {
      "label": "The Intact Pathway",
      "short": "Intact",
      "n": 140,
      "color": "#5b93c7",
      "bg": "rgba(91,147,199,0.12)",
      "emoji": "🟢"
    },
    "circumcised": {
      "label": "The Circumcised Pathway",
      "short": "Circumcised",
      "n": 210,
      "color": "#d94f4f",
      "bg": "rgba(217,79,79,0.12)",
      "emoji": "🔵"
    },
    "restoring": {
      "label": "The Restoration Pathway",
      "short": "Restoring",
      "n": 109,
      "color": "#e8c868",
      "bg": "rgba(232,200,104,0.12)",
      "emoji": "🟣"
    },
    "observer": {
      "label": "The Observer, Partner & Ally Pathway",
      "short": "Observer",
      "n": 37,
      "color": "#a0a0a0",
      "bg": "rgba(160,160,160,0.12)",
      "emoji": "🟠"
    },
    "born_circ": {
      "label": "Born Circumcised (Combined)",
      "short": "Born Circ.",
      "n": 319,
      "color": "#cc6855",
      "bg": "rgba(204,104,85,0.12)",
      "emoji": "🔵🟣"
    }
  },
  "questions": [
    {
      "id": "appearance",
      "cat": "Body Image",
      "q": "How do you feel about your penis's physical appearance?",
      "opts": [
        "Very Positive",
        "Positive",
        "Neutral",
        "Negative",
        "Don't think about it",
        "Very Negative"
      ],
      "colors": [
        "#5b93c7",
        "#8bb8d9",
        "#e8c868",
        "#e8a44a",
        "#d94f4f",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          62,
          45,
          19,
          12,
          1,
          0
        ],
        "circumcised": [
          23,
          54,
          32,
          51,
          2,
          44
        ],
        "restoring": [
          5,
          27,
          22,
          33,
          0,
          20
        ]
      },
      "pathways": [
        "intact",
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "pride",
      "cat": "Body Image",
      "q": "Overall, how proud or satisfied are you with your penis?",
      "opts": [
        "Very proud",
        "Generally proud",
        "Neutral",
        "Somewhat dissatisfied",
        "No framework",
        "Very dissatisfied"
      ],
      "colors": [
        "#5b93c7",
        "#8bb8d9",
        "#e8c868",
        "#e8a44a",
        "#d94f4f",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          53,
          51,
          16,
          13,
          3,
          1
        ],
        "circumcised": [
          17,
          51,
          24,
          46,
          5,
          63
        ],
        "restoring": [
          8,
          18,
          13,
          40,
          2,
          26
        ]
      },
      "sub": "Considering appearance, function, and pleasure",
      "pathways": [
        "intact",
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "intensity",
      "cat": "Sexual Experience",
      "q": "Intensity of Orgasm (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.73,
        "circumcised": 2.99,
        "restoring": 2.93
      }
    },
    {
      "id": "duration_r",
      "cat": "Sexual Experience",
      "q": "Duration of Orgasm (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.8,
        "circumcised": 2.81,
        "restoring": 2.65
      }
    },
    {
      "id": "ease",
      "cat": "Sexual Experience",
      "q": "Ease of Reaching Orgasm (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.43,
        "circumcised": 2.91,
        "restoring": 2.8
      }
    },
    {
      "id": "light",
      "cat": "Sexual Experience",
      "q": "Sensitivity to Light Touch (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.67,
        "circumcised": 2.6,
        "restoring": 2.67
      }
    },
    {
      "id": "mobile",
      "cat": "Sexual Experience",
      "q": "Pleasure from Mobile Skin / Gliding (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.88,
        "circumcised": 2.49,
        "restoring": 3.0
      }
    },
    {
      "id": "variety",
      "cat": "Sexual Experience",
      "q": "Variety of Pleasurable Sensations (1–5 scale)",
      "type": "avg",
      "data": {
        "intact": 3.78,
        "circumcised": 2.58,
        "restoring": 2.65
      }
    },
    {
      "id": "confidence",
      "cat": "Sexual Experience",
      "q": "How confident are you that your orgasms are as good as they could be?",
      "opts": [
        "Confident",
        "Extremely confident",
        "Moderately confident",
        "Depends",
        "Something is missing"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7"
      ],
      "data": {
        "intact": [
          58,
          33,
          22,
          15,
          6
        ],
        "circumcised": [
          32,
          13,
          46,
          12,
          96
        ],
        "restoring": [
          8,
          6,
          20,
          8,
          62
        ]
      },
      "pathways": [
        "intact",
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "lube",
      "cat": "Sexual Experience",
      "q": "How often do you need artificial lubrication?",
      "opts": [
        "Never",
        "Sometimes",
        "Rarely",
        "Often helpful",
        "Always/almost always",
        "N/A"
      ],
      "colors": [
        "#5b93c7",
        "#8bb8d9",
        "#e8c868",
        "#e8a44a",
        "#d94f4f",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          76,
          27,
          25,
          7,
          2,
          0
        ],
        "circumcised": [
          11,
          40,
          29,
          36,
          78,
          6
        ],
        "restoring": [
          17,
          19,
          19,
          15,
          35,
          1
        ]
      },
      "pathways": [
        "intact",
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "duration",
      "cat": "Sexual Experience",
      "q": "How long do the primary pleasurable sensations of your typical orgasm last?",
      "opts": [
        "6–15 sec",
        "16–30 sec",
        "0–5 sec",
        "Up to 1 min",
        "Unsure",
        "Varies",
        "1+ min"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          56,
          40,
          20,
          9,
          7,
          4,
          2
        ],
        "circumcised": [
          70,
          26,
          77,
          14,
          3,
          7,
          4
        ],
        "restoring": [
          40,
          12,
          41,
          4,
          3,
          3,
          2
        ]
      },
      "pathways": [
        "intact",
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "sons",
      "cat": "Autonomy & Ethics",
      "q": "If you were to have a male child, what would you choose regarding circumcision?",
      "opts": [
        "Keep intact",
        "N/A",
        "Undecided",
        "Partner's choice",
        "Circumcise"
      ],
      "colors": [
        "#5b93c7",
        "#d94f4f",
        "#e8c868",
        "#e8a44a",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          119,
          10,
          3,
          2,
          0
        ],
        "circumcised": [
          157,
          12,
          8,
          7,
          17
        ],
        "restoring": [
          105,
          2,
          0,
          0,
          0
        ],
        "observer": [
          30,
          1,
          0,
          1,
          1
        ]
      }
    },
    {
      "id": "autonomy",
      "cat": "Autonomy & Ethics",
      "q": "For a non-therapeutic irreversible procedure on a healthy infant — which principle takes priority?",
      "opts": [
        "Child's bodily autonomy",
        "Parental / medical discretion"
      ],
      "colors": [
        "#5b93c7",
        "#d94f4f"
      ],
      "data": {
        "intact": [
          132,
          5
        ],
        "circumcised": [
          161,
          37
        ],
        "restoring": [
          106,
          0
        ],
        "observer": [
          32,
          1
        ]
      }
    },
    {
      "id": "handled",
      "cat": "Decision & Consent",
      "q": "How was circumcision handled around the time of your birth?",
      "opts": [
        "Routine / automatic",
        "No idea",
        "Strong medical rec.",
        "Not brought up",
        "Neutral pros & cons"
      ],
      "colors": [
        "#d94f4f",
        "#a0a0a0",
        "#e8a44a",
        "#8bb8d9",
        "#5b93c7"
      ],
      "data": {
        "circumcised": [
          88,
          43,
          35,
          14,
          5
        ]
      },
      "note": "Asked of Circumcised Pathway respondents only.",
      "pathways": [
        "circumcised"
      ]
    },
    {
      "id": "norm",
      "cat": "Decision & Consent",
      "q": "In your community growing up, what was the general expectation for newborn boys?",
      "opts": [
        "Uncommon",
        "Unquestioned norm",
        "Very common",
        "50/50",
        "Not sure"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7"
      ],
      "data": {
        "intact": [
          46,
          32,
          31,
          17,
          10
        ],
        "circumcised": [
          46,
          95,
          29,
          12,
          19
        ],
        "restoring": [
          18,
          59,
          18,
          3,
          11
        ],
        "observer": [
          4,
          15,
          11,
          2,
          2
        ]
      }
    },
    {
      "id": "father_status",
      "cat": "Decision & Consent",
      "q": "What is your father's circumcision state?",
      "opts": [
        "Circumcised",
        "Intact",
        "Don't know",
        "N/A"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9"
      ],
      "data": {
        "circumcised": [
          139,
          50,
          16,
          2
        ],
        "restoring": [
          82,
          17,
          8,
          2
        ]
      },
      "note": "Asked of Circumcised and Restoring respondents.",
      "pathways": [
        "circumcised",
        "restoring"
      ]
    },
    {
      "id": "restoration_considered",
      "cat": "Decision & Consent",
      "q": "Have you ever considered or researched foreskin restoration?",
      "opts": [
        "Actively researching",
        "Seriously considered",
        "Briefly considered",
        "Never considered",
        "No",
        "Unsure/never heard"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7",
        "#a0a0a0"
      ],
      "data": {
        "circumcised": [
          56,
          49,
          47,
          32,
          16,
          4
        ]
      },
      "note": "Asked of Circumcised Pathway respondents only.",
      "pathways": [
        "circumcised"
      ]
    },
    {
      "id": "aesthetics",
      "cat": "Beliefs & Perceptions",
      "q": "Purely in terms of aesthetics, which look do you personally find more appealing?",
      "opts": [
        "Strongly prefer intact",
        "Slightly prefer intact",
        "No preference",
        "Slightly prefer circ",
        "Strongly prefer circ"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7"
      ],
      "data": {
        "intact": [
          90,
          20,
          11,
          9,
          8
        ],
        "circumcised": [
          106,
          22,
          19,
          16,
          41
        ],
        "restoring": [
          97,
          3,
          4,
          2,
          1
        ],
        "observer": [
          16,
          4,
          6,
          5,
          2
        ]
      }
    },
    {
      "id": "med_superior",
      "cat": "Beliefs & Perceptions",
      "q": "Which state do you believe is medically or hygienically superior?",
      "opts": [
        "Intact slightly",
        "Intact significantly",
        "No difference",
        "Circ slightly",
        "Circ significantly",
        "Unsure"
      ],
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7",
        "#a0a0a0"
      ],
      "data": {
        "intact": [
          47,
          45,
          27,
          10,
          4,
          4
        ],
        "circumcised": [
          48,
          63,
          33,
          27,
          25,
          7
        ],
        "restoring": [
          31,
          52,
          15,
          6,
          3,
          1
        ],
        "observer": [
          5,
          16,
          8,
          2,
          1,
          1
        ]
      }
    }
  ],
  "mirrorPairs": [
    {
      "id": "resentment_mirror",
      "title": "Resentment vs Regret",
      "note": "We use 'resentment' for the Circumcised Pathway because the procedure was performed without their agency. We use 'regret' for the Intact Pathway because that is the word that could meaningfully apply to a state they grew into. This distinction was shaped by community feedback.",
      "left": {
        "pathway": "circumcised",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "No, never",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          112,
          43,
          33,
          17
        ]
      },
      "right": {
        "pathway": "intact",
        "q": "Have you ever wished you were circumcised, or felt regret about being intact?",
        "opts": [
          "No, never",
          "Rarely",
          "Sometimes",
          "Strong & frequent"
        ],
        "data": [
          86,
          25,
          16,
          12
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#5b93c7"
      ]
    },
    {
      "id": "restoring_resentment",
      "title": "Restoration Pathway: Resentment",
      "sub": "Every restoring respondent reports negative feelings — 0% 'No, never' (n=103)",
      "left": {
        "pathway": "restoring",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          82,
          16,
          5
        ]
      },
      "right": {
        "pathway": "circumcised",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "No, never",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          112,
          43,
          33,
          17
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#5b93c7"
      ]
    },
    {
      "id": "curiosity_mirror",
      "title": "Curiosity About the Other Anatomy",
      "left": {
        "pathway": "circumcised",
        "q": "Have you wondered what sex would be like with an intact penis?",
        "opts": [
          "Often wondered",
          "Before being circ",
          "Occasionally",
          "Happy as is",
          "Circ preferable",
          "Never thought"
        ],
        "data": [
          139,
          31,
          22,
          8,
          4,
          1
        ]
      },
      "right": {
        "pathway": "intact",
        "q": "Have you wondered what sex would be like if you were circumcised?",
        "opts": [
          "Occasionally",
          "Often wondered",
          "Intact preferable",
          "Happy as is",
          "Never thought"
        ],
        "data": [
          58,
          38,
          28,
          11,
          4
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7",
        "#a0a0a0"
      ]
    }
  ],
  "curatedSections": [
    {
      "id": "pleasure_gap",
      "title": "The Pleasure Gap",
      "desc": "Self-reported sexual experience ratings across pathways",
      "question_ids": [
        "mobile",
        "light",
        "variety",
        "ease",
        "intensity",
        "duration_r",
        "confidence"
      ]
    },
    {
      "id": "lubrication",
      "title": "The Lubrication Deficit",
      "desc": "Functional self-sufficiency by pathway",
      "question_ids": [
        "lube",
        "duration"
      ]
    },
    {
      "id": "resentment",
      "title": "Resentment & Regret",
      "desc": "The asymmetric weight of being chosen for vs born into",
      "question_ids": [
        "resentment_mirror",
        "restoring_resentment",
        "pride"
      ]
    },
    {
      "id": "generational",
      "title": "The Generational Break",
      "desc": "Future-son intentions across every pathway",
      "question_ids": [
        "sons",
        "father_status"
      ]
    },
    {
      "id": "autonomy_consensus",
      "title": "Bodily Autonomy Consensus",
      "desc": "Where all pathways converge",
      "question_ids": [
        "autonomy"
      ]
    },
    {
      "id": "systemic",
      "title": "The Systemic Failure",
      "desc": "How decisions were actually made",
      "question_ids": [
        "handled",
        "norm"
      ]
    },
    {
      "id": "perception",
      "title": "Cross-Pathway Perception",
      "desc": "How each pathway sees the other and the aesthetic landscape",
      "question_ids": [
        "curiosity_mirror",
        "aesthetics",
        "med_superior"
      ]
    }
  ]
};

export const META             = _data.meta;
export const PATHWAY          = _data.pathway;
export const ALL_QUESTIONS    = _data.questions;
export const MIRROR_PAIRS     = _data.mirrorPairs;
export const CURATED_SECTIONS = _data.curatedSections;

// ── Curated quotes — reviewed by Tone, never auto-generated ──
export const QUOTE_GALLERIES = {
  resentment_mirror: {
    circumcised: [
      { text: "Pain. Loss of pleasure. Loss of confidence. Loss of trust. Self hatred. Depression.", context: "On drawbacks" },
      { text: "I, at 57 years old, have never had a normal intimate relationship... the mutilation is always there.", context: "On lifelong impact" },
      { text: "Negative impact to how I experience pleasure. Not being able to experience the build-up to orgasm from 0–10.", context: "On sensory experience" },
    ],
    intact: [
      { text: "In childhood and through college I was self conscious because all of my friends were cut and I only knew one other kid who was uncut.", context: "On regret triggers" },
      { text: "Only as a teen/young adult due to stigma arising from movies, pop culture, etc.", context: "On the source of regret" },
    ],
  },
  pride: {
    circumcised: [
      { text: "Sexual problems, skin tearing, not enough skin to accommodate it, low self esteem, avoiding intimacy.", context: "On daily reality" },
    ],
    intact: [
      { text: "Felt awkward in high school but never a concern.", context: "On growing up intact" },
    ],
  },
};
