"""The 6502 music player + song data, assembled for any load address.

Memory map of the generated binary (load address = base):
  base+0   JMP init      ; call once (A ignored; in a multi-tune build A = tune 0..n-1)
  base+3   JMP play      ; call once per frame (raster IRQ / VBI)
  base+6   frame_lo      ; 16-bit frame counter, incremented by every play call.
  base+7   frame_hi      ;   Read it from the game to sync events to the music.
  ...      player code, frequency table, instruments, wavetable, variables, song

Zero page: 2 bytes at `zp` (default $FB/$FC) are used as a temporary pointer
during play; nothing is kept there between calls.
"""

from __future__ import annotations

from .asm6502 import Asm, lo, hi, L
from .instruments import Instrument

SID = 0xD400
PAL_CLOCK = 985248
NTSC_CLOCK = 1022727


def freq_table(clock, tuning_semitones=0.0):
    """97 entries: note 0 = C-0 (MIDI 12) ... 96 = C-8."""
    out = []
    for i in range(97):
        hz = 440.0 * 2 ** ((i + 12 - 69 + tuning_semitones) / 12)
        out.append(min(0xFFFF, int(round(hz * 16777216 / clock))))
    return out


VARS = [
    # per voice (3 bytes each)
    ("ptr_lo", 3), ("ptr_hi", 3), ("delay", 3), ("ret_lo", 3), ("ret_hi", 3), ("callcnt", 3),
    ("inst", 3), ("note", 3), ("arpn", 3), ("arppos", 3), ("arpnotes", 12), ("wtpos", 3),
    ("frames", 3), ("gate", 3), ("vib_cnt", 3), ("vib_dir", 3), ("vib_off_lo", 3),
    ("vib_off_hi", 3), ("pw_lo", 3), ("pw_hi", 3), ("pw_dir", 3), ("cur_ctrl", 3),
    # globals / temps
    ("gptr_lo", 1), ("gptr_hi", 1), ("gdelay", 1), ("sidy", 1), ("curnote", 1), ("curwave", 1),
    ("flo", 1), ("fhi", 1), ("dlo", 1), ("dhi", 1), ("tmp", 1), ("tmp2", 1), ("cnt", 1),
    ("vib_ok", 1), ("srcy", 1), ("dst", 1),
]


def encode_instruments(insts: list[Instrument]):
    """Flatten instruments into parallel byte tables + a shared wavetable."""
    wt_wave, wt_note = [0], [0]                 # index 0 = "no table"
    cols = {k: [] for k in ("ad", "sr", "wave", "pwlo", "pwhi", "pwspeed", "pwmin", "pwmax",
                            "vibdelay", "vibdepth", "vibspeed", "wt")}
    for ins in insts:
        cols["ad"].append(ins.ad & 0xFF)
        cols["sr"].append(ins.sr & 0xFF)
        cols["wave"].append(ins.wave & 0xFE)
        cols["pwlo"].append(ins.pw & 0xFF)
        cols["pwhi"].append((ins.pw >> 8) & 0x0F)
        cols["pwspeed"].append(min(255, ins.pw_speed))
        cols["pwmin"].append((ins.pw_min >> 8) & 0x0F)
        cols["pwmax"].append((ins.pw_max >> 8) & 0x0F)
        depth = ins.vib_depth if ins.vib_depth else 0
        cols["vibdelay"].append(min(255, ins.vib_delay))
        cols["vibdepth"].append(depth)
        cols["vibspeed"].append(max(1, ins.vib_speed) if depth else 1)
        if ins.table:
            cols["wt"].append(len(wt_wave))
            for wave, note in ins.table:
                wt_wave.append(wave & 0xFE or 0x10)
                if isinstance(note, str) and note.startswith("abs:"):
                    wt_note.append(0x80 | (int(note[4:]) & 0x7F))
                else:
                    wt_note.append((int(note) + 0x40) & 0x7F)
            wt_wave.append(0)                   # terminator
            wt_note.append(0)
        else:
            cols["wt"].append(0)
    if len(wt_wave) > 255:
        raise ValueError("wavetable too large")
    return cols, wt_wave, wt_note


def build_player(base, insts, song_items, clock=PAL_CLOCK, tuning=0.0, zp=0xFB, loop=True,
                 layout_fn=None, n_songs=1):
    """Assemble player + data. `layout_fn(addr)` returns (song_bytes, stream_starts):
    4 streams (3 voices + global) per tune, tune after tune."""
    a = Asm(base)
    a.equ("ZP", zp)
    a.equ("SID", SID)

    a.op("jmp", "abs", "init")
    a.op("jmp", "abs", "play")
    a.label("frame_lo"); a.byte(0)
    a.label("frame_hi"); a.byte(0)

    # ------------------------------------------------------------- init
    a.label("init")
    if n_songs > 1:
        # A = tune number: remember its offset into the stream tables
        a.op("cmp", "#", n_songs)
        a.op("bcc", "init_song")
        a.op("lda", "#", 0)
        a.label("init_song")
        a.op("asl", "acc")
        a.op("asl", "acc")
        a.op("sta", "abs", "song_ofs")
    a.op("lda", "#", 0)
    a.op("tax")
    a.label("init_clr")
    a.op("sta", "abs", "vars", x=True)
    a.op("inx")
    a.op("cpx", "#", "VARS_LEN")
    a.op("bne", "init_clr")
    a.op("sta", "abs", "frame_lo")
    a.op("sta", "abs", "frame_hi")
    a.op("ldx", "#", 0x18)
    a.label("init_sid")
    a.op("sta", "abs", SID, x=True)
    a.op("dex")
    a.op("bpl", "init_sid")
    a.op("lda", "#", 0x0F)
    a.op("sta", "abs", SID + 0x18)
    a.op("ldx", "#", 2)
    a.label("init_v")
    if n_songs > 1:
        a.op("txa")
        a.op("clc")
        a.op("adc", "abs", "song_ofs")
        a.op("tay")
        a.op("lda", "abs", "stream_lo", y=True)
        a.op("sta", "abs", "ptr_lo", x=True)
        a.op("lda", "abs", "stream_hi", y=True)
    else:
        a.op("lda", "abs", "stream_lo", x=True)
        a.op("sta", "abs", "ptr_lo", x=True)
        a.op("lda", "abs", "stream_hi", x=True)
    a.op("sta", "abs", "ptr_hi", x=True)
    a.op("lda", "#", 1)
    a.op("sta", "abs", "delay", x=True)
    a.op("dex")
    a.op("bpl", "init_v")
    if n_songs > 1:
        a.op("ldy", "abs", "song_ofs")
        a.op("lda", "abs", L("stream_lo", 3), y=True)
        a.op("sta", "abs", "gptr_lo")
        a.op("lda", "abs", L("stream_hi", 3), y=True)
    else:
        a.op("lda", "abs", L("stream_lo", 3))
        a.op("sta", "abs", "gptr_lo")
        a.op("lda", "abs", L("stream_hi", 3))
    a.op("sta", "abs", "gptr_hi")
    a.op("lda", "#", 1)
    a.op("sta", "abs", "gdelay")
    a.op("rts")

    # ------------------------------------------------------------- play
    a.label("play")
    a.op("inc", "abs", "frame_lo")
    a.op("bne", "play_g")
    a.op("inc", "abs", "frame_hi")
    a.label("play_g")
    a.op("dec", "abs", "gdelay")
    a.op("bne", "play_voices")
    a.op("lda", "abs", "gptr_lo"); a.op("sta", "zp", "ZP")
    a.op("lda", "abs", "gptr_hi"); a.op("sta", "zp", zp + 1)
    a.label("g_read")
    a.op("ldy", "#", 0)
    a.op("lda", "(zp),y", "ZP")
    a.op("cmp", "#", 0x10)
    a.op("bcs", "g_notvol")
    a.op("sta", "abs", SID + 0x18)
    a.op("jmp", "abs", "g_timed")
    a.label("g_notvol")
    a.op("cmp", "#", 0x62)
    a.op("beq", "g_timed")
    a.op("cmp", "#", 0x68)
    a.op("bne", "g_end")
    a.op("iny"); a.op("lda", "(zp),y", "ZP"); a.op("pha")
    a.op("iny"); a.op("lda", "(zp),y", "ZP"); a.op("sta", "zp", zp + 1)
    a.op("pla"); a.op("sta", "zp", "ZP")
    a.op("jmp", "abs", "g_read")
    a.label("g_end")
    a.op("lda", "#", 255)
    a.op("sta", "abs", "gdelay")
    a.op("jmp", "abs", "g_save")
    a.label("g_timed")
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "gdelay")
    a.op("lda", "zp", "ZP"); a.op("clc"); a.op("adc", "#", 2); a.op("sta", "zp", "ZP")
    a.op("bcc", "g_save")
    a.op("inc", "zp", zp + 1)
    a.label("g_save")
    a.op("lda", "zp", "ZP"); a.op("sta", "abs", "gptr_lo")
    a.op("lda", "zp", zp + 1); a.op("sta", "abs", "gptr_hi")
    a.label("play_voices")
    a.op("ldx", "#", 2)
    a.label("play_vloop")
    a.op("jsr", "abs", "voice")
    a.op("dex")
    a.op("bpl", "play_vloop")
    a.op("rts")

    # ------------------------------------------------------------- voice
    a.label("voice")
    a.op("lda", "abs", "sidoff", x=True)
    a.op("sta", "abs", "sidy")
    a.op("dec", "abs", "delay", x=True)
    a.op("beq", "v_fetch")
    a.op("jmp", "abs", "effects")
    a.label("v_fetch")
    a.op("lda", "abs", "ptr_lo", x=True); a.op("sta", "zp", "ZP")
    a.op("lda", "abs", "ptr_hi", x=True); a.op("sta", "zp", zp + 1)
    a.label("v_read")
    a.op("ldy", "#", 0)
    a.op("lda", "(zp),y", "ZP")
    a.op("cmp", "#", 0x60)
    a.op("bcs", "v_notnote")
    # NOTE n dd
    a.op("sta", "abs", "note", x=True)
    a.op("lda", "#", 0)
    a.op("sta", "abs", "arpn", x=True)
    a.op("jsr", "abs", "trigger")
    a.op("jmp", "abs", "v_timed")
    a.label("v_notnote")
    a.op("bne", "v_n61")
    # $60 OFF
    a.op("lda", "#", 0)
    a.op("sta", "abs", "gate", x=True)
    a.op("jmp", "abs", "v_timed")
    a.label("v_n61")
    a.op("cmp", "#", 0x61)
    a.op("bne", "v_n62")
    # $61 HARD RESTART
    a.op("lda", "#", 0)
    a.op("sta", "abs", "gate", x=True)
    a.op("ldy", "abs", "sidy")
    a.op("sta", "abs", SID + 5, y=True)
    a.op("sta", "abs", SID + 6, y=True)
    a.op("jmp", "abs", "v_timed")
    a.label("v_n62")
    a.op("cmp", "#", 0x62)
    a.op("bne", "v_n63")
    a.op("jmp", "abs", "v_timed")                # WAIT
    a.label("v_n63")
    a.op("cmp", "#", 0x63)
    a.op("bne", "v_n64")
    # $63 INSTR ii
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "inst", x=True)
    a.op("lda", "#", 2)
    a.op("jsr", "abs", "advance")
    a.op("jmp", "abs", "v_read")
    a.label("v_n64")
    a.op("cmp", "#", 0x64)
    a.op("bne", "v_n65")
    # $64 LEGATO nn dd
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "note", x=True)
    a.op("lda", "#", 0)
    a.op("sta", "abs", "arpn", x=True)
    a.op("ldy", "#", 2)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "delay", x=True)
    a.op("lda", "#", 3)
    a.op("jmp", "abs", "v_adv_wait")
    a.label("v_n65")
    a.op("cmp", "#", 0x67)
    a.op("bcc", "v_arp")
    a.op("jmp", "abs", "v_n67")
    # $65/$66 ARP kk n1..nk dd
    a.label("v_arp")
    a.op("sta", "abs", "tmp2")                   # opcode
    a.op("txa"); a.op("asl", "acc"); a.op("asl", "acc")
    a.op("sta", "abs", "dst")
    a.op("lda", "#", 2)
    a.op("sta", "abs", "srcy")
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "arpn", x=True)
    a.op("sta", "abs", "cnt")
    a.label("v_arpcopy")
    a.op("ldy", "abs", "srcy")
    a.op("lda", "(zp),y", "ZP")
    a.op("ldy", "abs", "dst")
    a.op("sta", "abs", "arpnotes", y=True)
    a.op("inc", "abs", "srcy")
    a.op("inc", "abs", "dst")
    a.op("dec", "abs", "cnt")
    a.op("bne", "v_arpcopy")
    a.op("ldy", "abs", "srcy")
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "delay", x=True)
    a.op("inc", "abs", "srcy")                   # srcy = command length
    a.op("lda", "#", 0)
    a.op("sta", "abs", "arppos", x=True)
    a.op("txa"); a.op("asl", "acc"); a.op("asl", "acc"); a.op("tay")
    a.op("lda", "abs", "arpnotes", y=True)
    a.op("sta", "abs", "note", x=True)
    a.op("lda", "abs", "tmp2")
    a.op("cmp", "#", 0x65)
    a.op("bne", "v_arp_nt")
    a.op("jsr", "abs", "trigger")
    a.label("v_arp_nt")
    a.op("lda", "abs", "srcy")
    a.op("jmp", "abs", "v_adv_wait")
    a.label("v_n67")
    a.op("bne", "v_n68")
    # $67 CALL lo hi cc
    a.op("lda", "zp", "ZP"); a.op("clc"); a.op("adc", "#", 4)
    a.op("sta", "abs", "ret_lo", x=True)
    a.op("lda", "zp", zp + 1); a.op("adc", "#", 0)
    a.op("sta", "abs", "ret_hi", x=True)
    a.op("ldy", "#", 3)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "callcnt", x=True)
    a.label("v_jump")
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP"); a.op("pha")
    a.op("iny")
    a.op("lda", "(zp),y", "ZP"); a.op("sta", "zp", zp + 1)
    a.op("pla"); a.op("sta", "zp", "ZP")
    a.op("jmp", "abs", "v_read")
    a.label("v_n68")
    a.op("cmp", "#", 0x68)
    a.op("beq", "v_jump")
    # $69 END (and anything unknown): silence, re-check in 255 frames
    a.op("lda", "#", 0)
    a.op("sta", "abs", "gate", x=True)
    a.op("lda", "#", 255)
    a.op("sta", "abs", "delay", x=True)
    a.op("jmp", "abs", "v_save")
    a.label("v_timed")                           # op dd
    a.op("ldy", "#", 1)
    a.op("lda", "(zp),y", "ZP")
    a.op("sta", "abs", "delay", x=True)
    a.op("lda", "#", 2)
    a.label("v_adv_wait")
    a.op("jsr", "abs", "advance")
    a.label("v_save")
    a.op("lda", "zp", "ZP"); a.op("sta", "abs", "ptr_lo", x=True)
    a.op("lda", "zp", zp + 1); a.op("sta", "abs", "ptr_hi", x=True)
    a.op("jmp", "abs", "effects")

    # advance: ZP += A, then handle end of CALL body
    a.label("advance")
    a.op("clc")
    a.op("adc", "zp", "ZP")
    a.op("sta", "zp", "ZP")
    a.op("bcc", "adv_1")
    a.op("inc", "zp", zp + 1)
    a.label("adv_1")
    a.op("lda", "abs", "callcnt", x=True)
    a.op("beq", "adv_2")
    a.op("dec", "abs", "callcnt", x=True)
    a.op("bne", "adv_2")
    a.op("lda", "abs", "ret_lo", x=True); a.op("sta", "zp", "ZP")
    a.op("lda", "abs", "ret_hi", x=True); a.op("sta", "zp", zp + 1)
    a.label("adv_2")
    a.op("rts")

    # trigger: start the instrument's envelope for a new note
    a.label("trigger")
    a.op("ldy", "abs", "inst", x=True)
    a.op("lda", "abs", "inst_ad", y=True); a.op("sta", "abs", "tmp")
    a.op("lda", "abs", "inst_wt", y=True); a.op("sta", "abs", "wtpos", x=True)
    a.op("lda", "abs", "inst_pwlo", y=True); a.op("sta", "abs", "pw_lo", x=True)
    a.op("lda", "abs", "inst_pwhi", y=True); a.op("sta", "abs", "pw_hi", x=True)
    a.op("lda", "abs", "inst_vibspeed", y=True); a.op("sta", "abs", "vib_cnt", x=True)
    a.op("lda", "abs", "inst_sr", y=True)
    a.op("ldy", "abs", "sidy")
    a.op("sta", "abs", SID + 6, y=True)
    a.op("lda", "abs", "tmp")
    a.op("sta", "abs", SID + 5, y=True)
    a.comment("gate off for a moment: the envelope always restarts")
    a.op("lda", "abs", "cur_ctrl", x=True)
    a.op("and", "#", 0xFE)
    a.op("sta", "abs", SID + 4, y=True)
    a.op("lda", "#", 0)
    a.op("sta", "abs", "pw_dir", x=True)
    a.op("sta", "abs", "vib_dir", x=True)
    a.op("sta", "abs", "vib_off_lo", x=True)
    a.op("sta", "abs", "vib_off_hi", x=True)
    a.op("sta", "abs", "frames", x=True)
    a.op("lda", "#", 1)
    a.op("sta", "abs", "gate", x=True)
    a.op("rts")

    # ------------------------------------------------------------- effects
    a.label("effects")
    a.op("lda", "#", 0)
    a.op("sta", "abs", "vib_ok")
    a.op("lda", "abs", "arpn", x=True)
    a.op("beq", "fx_noarp")
    a.op("txa"); a.op("asl", "acc"); a.op("asl", "acc")
    a.op("clc"); a.op("adc", "abs", "arppos", x=True); a.op("tay")
    a.op("lda", "abs", "arpnotes", y=True)
    a.op("sta", "abs", "curnote")
    a.op("inc", "abs", "arppos", x=True)
    a.op("lda", "abs", "arppos", x=True)
    a.op("cmp", "abs", "arpn", x=True)
    a.op("bcc", "fx_wt")
    a.op("lda", "#", 0)
    a.op("sta", "abs", "arppos", x=True)
    a.op("beq", "fx_wt")
    a.label("fx_noarp")
    a.op("lda", "abs", "note", x=True)
    a.op("sta", "abs", "curnote")
    a.op("inc", "abs", "vib_ok")
    a.label("fx_wt")
    a.op("ldy", "abs", "inst", x=True)
    a.op("lda", "abs", "inst_wave", y=True)
    a.op("sta", "abs", "curwave")
    a.op("lda", "abs", "wtpos", x=True)
    a.op("beq", "fx_freq")
    a.op("tay")
    a.op("lda", "#", 0)
    a.op("sta", "abs", "vib_ok")
    a.op("lda", "abs", "wt_wave", y=True)
    a.op("sta", "abs", "curwave")
    a.op("lda", "abs", "wt_note", y=True)
    a.op("bmi", "fx_wtabs")
    a.op("clc"); a.op("adc", "abs", "curnote"); a.op("sec"); a.op("sbc", "#", 0x40)
    a.op("jmp", "abs", "fx_wtclamp")
    a.label("fx_wtabs")
    a.op("and", "#", 0x7F)
    a.label("fx_wtclamp")
    a.op("cmp", "#", 96)
    a.op("bcc", "fx_wtset")
    a.op("cmp", "#", 0xC0)
    a.op("lda", "#", 95)
    a.op("bcc", "fx_wtset")
    a.op("lda", "#", 0)
    a.label("fx_wtset")
    a.op("sta", "abs", "curnote")
    a.op("lda", "abs", L("wt_wave", 1), y=True)
    a.op("beq", "fx_wtend")
    a.op("inc", "abs", "wtpos", x=True)
    a.op("bne", "fx_freq")
    a.label("fx_wtend")
    a.op("sta", "abs", "wtpos", x=True)
    a.label("fx_freq")
    a.op("ldy", "abs", "curnote")
    a.op("lda", "abs", "freq_lo", y=True); a.op("sta", "abs", "flo")
    a.op("lda", "abs", "freq_hi", y=True); a.op("sta", "abs", "fhi")
    # vibrato
    a.op("lda", "abs", "vib_ok")
    a.op("beq", "fx_novib")
    a.op("ldy", "abs", "inst", x=True)
    a.op("lda", "abs", "inst_vibdepth", y=True)
    a.op("beq", "fx_novib")
    a.op("sta", "abs", "cnt")
    a.op("lda", "abs", "frames", x=True)
    a.op("cmp", "abs", "inst_vibdelay", y=True)
    a.op("bcc", "fx_novib")
    a.op("ldy", "abs", "curnote")
    a.op("lda", "abs", L("freq_lo", 1), y=True); a.op("sec"); a.op("sbc", "abs", "freq_lo", y=True)
    a.op("sta", "abs", "dlo")
    a.op("lda", "abs", L("freq_hi", 1), y=True); a.op("sbc", "abs", "freq_hi", y=True)
    a.op("sta", "abs", "dhi")
    a.label("fx_vshift")
    a.op("lsr", "abs", "dhi")
    a.op("ror", "abs", "dlo")
    a.op("dec", "abs", "cnt")
    a.op("bne", "fx_vshift")
    a.op("lda", "abs", "vib_dir", x=True)
    a.op("bne", "fx_vsub")
    a.op("lda", "abs", "vib_off_lo", x=True); a.op("clc"); a.op("adc", "abs", "dlo")
    a.op("sta", "abs", "vib_off_lo", x=True)
    a.op("lda", "abs", "vib_off_hi", x=True); a.op("adc", "abs", "dhi")
    a.op("sta", "abs", "vib_off_hi", x=True)
    a.op("jmp", "abs", "fx_vcnt")
    a.label("fx_vsub")
    a.op("lda", "abs", "vib_off_lo", x=True); a.op("sec"); a.op("sbc", "abs", "dlo")
    a.op("sta", "abs", "vib_off_lo", x=True)
    a.op("lda", "abs", "vib_off_hi", x=True); a.op("sbc", "abs", "dhi")
    a.op("sta", "abs", "vib_off_hi", x=True)
    a.label("fx_vcnt")
    a.op("dec", "abs", "vib_cnt", x=True)
    a.op("bne", "fx_vapply")
    a.op("ldy", "abs", "inst", x=True)
    a.op("lda", "abs", "inst_vibspeed", y=True)
    a.op("asl", "acc")
    a.op("sta", "abs", "vib_cnt", x=True)
    a.op("lda", "abs", "vib_dir", x=True)
    a.op("eor", "#", 1)
    a.op("sta", "abs", "vib_dir", x=True)
    a.label("fx_vapply")
    a.op("lda", "abs", "flo"); a.op("clc"); a.op("adc", "abs", "vib_off_lo", x=True)
    a.op("sta", "abs", "flo")
    a.op("lda", "abs", "fhi"); a.op("adc", "abs", "vib_off_hi", x=True)
    a.op("sta", "abs", "fhi")
    a.label("fx_novib")
    a.op("lda", "abs", "frames", x=True)
    a.op("cmp", "#", 255)
    a.op("beq", "fx_pw")
    a.op("inc", "abs", "frames", x=True)
    # pulse width modulation (bounces between min/max)
    a.label("fx_pw")
    a.op("ldy", "abs", "inst", x=True)
    a.op("lda", "abs", "inst_pwspeed", y=True)
    a.op("beq", "fx_write")
    a.op("sta", "abs", "tmp")
    a.op("lda", "abs", "pw_dir", x=True)
    a.op("bne", "fx_pwdown")
    a.op("lda", "abs", "pw_lo", x=True); a.op("clc"); a.op("adc", "abs", "tmp")
    a.op("sta", "abs", "pw_lo", x=True)
    a.op("bcc", "fx_pwup2")
    a.op("inc", "abs", "pw_hi", x=True)
    a.label("fx_pwup2")
    a.op("lda", "abs", "pw_hi", x=True)
    a.op("cmp", "abs", "inst_pwmax", y=True)
    a.op("bcc", "fx_write")
    a.op("lda", "#", 1)
    a.op("sta", "abs", "pw_dir", x=True)
    a.op("bne", "fx_write")
    a.label("fx_pwdown")
    a.op("lda", "abs", "pw_lo", x=True); a.op("sec"); a.op("sbc", "abs", "tmp")
    a.op("sta", "abs", "pw_lo", x=True)
    a.op("bcs", "fx_pwdn2")
    a.op("dec", "abs", "pw_hi", x=True)
    a.label("fx_pwdn2")
    a.op("lda", "abs", "pw_hi", x=True)
    a.op("cmp", "abs", "inst_pwmin", y=True)
    a.op("bcs", "fx_write")
    a.op("lda", "#", 0)
    a.op("sta", "abs", "pw_dir", x=True)
    a.label("fx_write")
    a.op("ldy", "abs", "sidy")
    a.op("lda", "abs", "flo"); a.op("sta", "abs", SID + 0, y=True)
    a.op("lda", "abs", "fhi"); a.op("sta", "abs", SID + 1, y=True)
    a.op("lda", "abs", "pw_lo", x=True); a.op("sta", "abs", SID + 2, y=True)
    a.op("lda", "abs", "pw_hi", x=True); a.op("sta", "abs", SID + 3, y=True)
    a.op("lda", "abs", "curwave")
    a.op("ora", "abs", "gate", x=True)
    a.op("sta", "abs", "cur_ctrl", x=True)
    a.op("sta", "abs", SID + 4, y=True)
    a.op("rts")

    # ------------------------------------------------------------- tables
    ft = freq_table(clock, tuning)
    a.label("sidoff"); a.byte(0, 7, 14)
    a.label("freq_lo"); a.byte(*[f & 0xFF for f in ft])
    a.label("freq_hi"); a.byte(*[f >> 8 for f in ft])
    cols, wt_wave, wt_note = encode_instruments(insts)
    for k, v in cols.items():
        a.label("inst_" + k)
        a.byte(*v)
    a.label("wt_wave"); a.byte(*wt_wave)
    a.label("wt_note"); a.byte(*wt_note)
    a.label("stream_lo"); a.byte(*[lo(f"stream{i}") for i in range(4 * n_songs)])
    a.label("stream_hi"); a.byte(*[hi(f"stream{i}") for i in range(4 * n_songs)])
    if n_songs > 1:
        a.label("song_ofs"); a.byte(0)
    a.label("vars")
    total = 0
    for name, size in VARS:
        a.label(name)
        a.byte(*([0] * size))
        total += size
    a.equ("VARS_LEN", total)

    # ------------------------------------------------------------- song
    # two passes: lay out once to learn where the song starts
    a.label("song")
    labels = a.relax()
    song_addr = labels["song"]
    data, starts = layout_fn(song_addr)
    for i, s in enumerate(starts):
        a.equ(f"stream{i}", s)
    a.byte(*data)
    code = a.assemble()
    return code, a
